services:
  - type: web
    name: dhanhq-websocket
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: DHAN_ACCESS_TOKEN
        fromSecret: true
      - key: DHAN_CLIENT_ID
        fromSecret: true
